[project]
name = "chuk-math"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain-ollama>=0.2.2",
    "langchain>=0.3.15",
    "ollama>=0.4.7",
    "sympy>=1.13.3",
    "pytest>=8.3.4",
]
