class TokenType:
    NUMBER = 'NUMBER'
    OPERATOR = 'OPERATOR'
    PARENTHESIS = 'PARENTHESIS'
    IDENTIFIER = 'IDENTIFIER'
    FUNCTION = 'FUNCTION'
    WHITESPACE = 'WHITESPACE'
    UNKNOWN = 'UNKNOWN'